
export const Users = [
    {
        id: 1,
        profilePicture: "assets/person/image (1).jpg",
        username: "Yash Maske",
    },
    {
        id: 2,
        profilePicture: "assets/person/image (2).jpg",
        username: "Pola Foster",
    },
    {
        id: 3,
        profilePicture: "assets/person/image (3).jpg",
        username: "John Carter",
    },
    {
        id: 4,
        profilePicture: "assets/person/image (4).jpg",
        username: "Sarah Ahmed",
    },
    {
        id: 5,
        profilePicture: "assets/person/image (5).jpg",
        username: "Michael Brown",
    },
    {
        id: 6,
        profilePicture: "assets/person/image (6).jpg",
        username: "Emily Clark",
    },
    {
        id: 7,
        profilePicture: "assets/person/image (7).jpg",
        username: "David Warner",
    },
    {
        id: 8,
        profilePicture: "assets/person/image (8).jpg",
        username: "Sophia Turner",
    },
    {
        id: 9,
        profilePicture: "assets/person/image (9).jpg",
        username: "James Wilson",
    },
    {
        id: 10,
        profilePicture: "assets/person/image (10).jpg",
        username: "Olivia Martinez",
    },
];
export const Posts = [
    {
        id: 1,
        desc: "Love For All Hatred For None.",
        photo: "assets/post/image (1).jpg",
        date: "5 mins ago",
        userId: 1,
        like: 32,
        comment: 9,
    },
    {
        id: 2,
        photo: "assets/post/image (2).jpg",
        date: "15 mins ago",
        userId: 2,
        like: 25,
        comment: 4,
    },
    {
        id: 3,
        desc: "Every moment is a fresh beginning.",
        photo: "assets/post/image (3).jpg",
        date: "20 mins ago",
        userId: 3,
        like: 45,
        comment: 12,
    },
    {
        id: 4,
        desc: "Dream big, work hard.",
        photo: "assets/post/image (4).jpg",
        date: "30 mins ago",
        userId: 4,
        like: 18,
        comment: 3,
    },
    {
        id: 5,
        photo: "assets/post/image (5).jpg",
        date: "45 mins ago",
        userId: 5,
        like: 11,
        comment: 2,
    },
    {
        id: 6,
        desc: "Happiness is homemade.",
        photo: "assets/post/image (6).jpg",
        date: "1 hour ago",
        userId: 6,
        like: 39,
        comment: 7,
    },
    {
        id: 7,
        desc: "Be yourself; everyone else is already taken.",
        photo: "assets/post/image (7).jpg",
        date: "2 hours ago",
        userId: 7,
        like: 52,
        comment: 15,
    },
    {
        id: 8,
        photo: "assets/post/image (8).jpg",
        date: "3 hours ago",
        userId: 8,
        like: 28,
        comment: 6,
    },
    {
        id: 9,
        desc: "Let your dreams be your wings.",
        photo: "assets/post/image (9).jpg",
        date: "4 hours ago",
        userId: 9,
        like: 21,
        comment: 5,
    },
    {
        id: 10,
        desc: "Stay positive, work hard, make it happen.",
        photo: "assets/post/image (10).jpg",
        date: "5 hours ago",
        userId: 10,
        like: 37,
        comment: 10,
    },
];
